### PR TITLE
Improve image upload

### PR DESCRIPTION
**Pull request by mth-1012**
## Description
General improvement on Multer middleware
- Limits for number of files: 5
- Limits for form-data size: 10 MB
- Limits for form-data files: image types only
- Image upload performed after input validation

### CODE REVIEW

**Review by AC159 — CHANGES_REQUESTED** [review]
The request attributes have not changed according to what we are sending from the android application and I cannot approve until it is added

**Comment by AC159** [comment]
@mth-1012 By the way, I tested your code a bit further and the request images are still uploaded even after a failing request validation, so yeah, it doesn't seem to work as you expected

**Comment by mth-1012** [comment]
Please re-review the PR. I've made some changes. Lmk if there's still any problem

**Review by AC159 — APPROVED** [review]
Everything works!

**Pull request merged**
